### ISSUE TITLE
这个是什么意思，怎么解决

### ISSUE THREAD

**Issue by busyhe** [cxphoe/ie8-cli#2]
![image](https://user-images.githubusercontent.com/17348825/101275757-2dc63380-37e3-11eb-99d4-949acc35c22c.png)

**Comment by Ethan-Fung** [comment]
![image](https://user-images.githubusercontent.com/25811764/102448637-88764f80-406d-11eb-92f7-a00c41fc4752.png)
当我运行dev:ie8，没法运行。怎么解决？

**Comment by busyhe** [comment]
已放弃
